### ISSUE TITLE
xmldoc error

### ISSUE THREAD

**Issue by tgarijo** [nfarina/xmldoc#19]
First Thank you very much for your job with xmldoc.

I have an error when I run my program at second time.

My program run http server and call xmdoc for read a xml stream. In the first petition I don’t have any problem but when I received the second petition I have this error 
W:\Source\Tgarijo\javascript\proyectos\nodejs\node_modules\xmldoc\lib\xmldoc.js:
219
function parser_text() { delegates[0]._text.apply(delegates[0],arguments) }
                                     ^
TypeError: Cannot read property '_text' of undefined
    at Object.parser_text [as ontext] (W:\Source\Tgarijo\javascript\proyectos\no
dejs\node_modules\xmldoc\lib\xmldoc.js:219:38)
    at emit (W:\Source\Tgarijo\javascript\proyectos\nodejs\node_modules\xmldoc\n
ode_modules\sax\lib\sax.js:615:33)
    at closeText (W:\Source\Tgarijo\javascript\proyectos\nodejs\node_modules\xml
doc\node_modules\sax\lib\sax.js:625:24)
    at emitNode (W:\Source\Tgarijo\javascript\proyectos\nodejs\node_modules\xmld
oc\node_modules\sax\lib\sax.js:619:24)
    at Object.write (W:\Source\Tgarijo\javascript\proyectos\nodejs\node_modules\
xmldoc\node_modules\sax\lib\sax.js:1153:11)
    at new XmlDocument (W:\Source\Tgarijo\javascript\proyectos\nodejs\node_modul
es\xmldoc\lib\xmldoc.js:184:15)
    at new OTA (W:\Source\Tgarijo\javascript\proyectos\nodejs\xmlOta.js:15:14)
    at W:\Source\Tgarijo\javascript\proyectos\nodejs\xmlEngine.js:45:27
    at IncomingMessage.<anonymous> (W:\Source\Tgarijo\javascript\proyectos\nodej
s\xmlEngine.js:22:13)
    at IncomingMessage.emit (events.js:104:17)

Please can you help me??

Best Regards

**Comment by tgarijo** [comment]
Hi, are there anybody that knows this error?

**Comment by nfarina** [comment]
Hello, I believe this is happening because `xmldoc` was not properly passing up XML errors generated by the underlying parser.

I'm closing this tentatively - could you try the latest `xmldoc` and if you still see this error, reopen the issue?
