### ISSUE TITLE
Support DOCTYPE or ignore it please

### ISSUE THREAD

**Issue by notsyncing** [nfarina/xmldoc#24]
Hello, I'm using xmldoc to parse XML files and it worked very well!
But I ran into a problem... 
when a XML document contains a DOCTYPE tag and there are more than one tag after it, xmldoc will throw an error, like following:

> var a = new xmldoc.XmlDocument("<!DOCTYPE x>&lt;b /&gt;&lt;a&gt;&lt;/a&gt;")
TypeError: Cannot read property '_opentag' of undefined
    at Object.parser_opentag as onopentag (/home/sfc/Projects/common-js/node-bubble/node_modules/xmldoc/lib/xmldoc.js:222:41)
    at emit (/home/sfc/Projects/common-js/node-bubble/node_modules/xmldoc/node_modules/sax/lib/sax.js:625:33)
    at emitNode (/home/sfc/Projects/common-js/node-bubble/node_modules/xmldoc/node_modules/sax/lib/sax.js:630:3)
    at openTag (/home/sfc/Projects/common-js/node-bubble/node_modules/xmldoc/node_modules/sax/lib/sax.js:814:3)
    at Object.write (/home/sfc/Projects/common-js/node-bubble/node_modules/xmldoc/node_modules/sax/lib/sax.js:1189:26)
    at new XmlDocument (/home/sfc/Projects/common-js/node-bubble/node_modules/xmldoc/lib/xmldoc.js:188:15)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)

docs like "<!DOCTYPE x><a></a>" and "<!DOCTYPE x><a><b></b></a>" do not produce this error.

Could you please add support for DOCTYPE tags, or just ignore them sliently?
Thank you very much!

using xmldoc 0.3.1 on nodejs 0.12.7

**Comment by notsyncing** [comment]
Found problem, XML doesn't support mutiple root elements...
Sorry for disturbing!

**Comment by nfarina** [comment]
👍
