### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by MartinDelille** [nfarina/xmldoc#44]
If I manage to make *xmldoc* to work in the browser, it doesn't play fine with *node*.

I have this very basic javascript file:

    // test.js
    var xmldoc = require('xmldoc');
    var root = '<root></root>';
    var doc = xmldoc.XmlDocument(root);

Unfortunately, when running the file with *node* it fails:

    $ node test.js
    /Users/martin/dev/lylo/test2/node_modules/xmldoc/lib/xmldoc.js:291
    function parser_opentag() { delegates[0] && delegates[0]._opentag.apply(delegates[0],arguments) }
                                                                     ^

    TypeError: Cannot read property 'apply' of undefined
        at SAXParser.parser_opentag [as onopentag] (/Users/martin/dev/lylo/test2/node_modules/xmldoc/lib/xmldoc.js:291:66)
        at emit (/Users/martin/dev/lylo/test2/node_modules/sax/lib/sax.js:640:35)
        at emitNode (/Users/martin/dev/lylo/test2/node_modules/sax/lib/sax.js:645:5)
        at openTag (/Users/martin/dev/lylo/test2/node_modules/sax/lib/sax.js:841:5)
        at SAXParser.write (/Users/martin/dev/lylo/test2/node_modules/sax/lib/sax.js:1291:15)
        at Object.XmlDocument (/Users/martin/dev/lylo/test2/node_modules/xmldoc/lib/xmldoc.js:251:15)
        at Object.<anonymous> (/Users/martin/dev/lylo/test2/test.js:4:18)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)

Am I doing something wrong? Is there any incompatibilities with my *node* version (7.4.0) ?

**Comment by nfarina** [comment]
I believe you need a `new` in front of your `XmlDocument` constructor. Example:

```
var doc = new xmldoc.XmlDocument(root);
```

**Comment by MartinDelille** [comment]
My mistake! Sorry for disturbing...

**Comment by a-veracataldo** [comment]
My mistake! Sorry for disturbing...
--


cual era el error ?

**Comment by a-veracataldo** [comment]
My mistake! Sorry for disturbing...




> My mistake! Sorry for disturbing...

what was the error?
