### ISSUE TITLE
new XmlDocument() throws error for valid XML Document

### ISSUE THREAD

**Issue by brandonkirsch** [nfarina/xmldoc#49]
I have a valid XML Document that causes xmldoc to trigger a TypeError when I try to parse it using new XmlDocument();

My XML Document:
`<?xml version="1.0" encoding="UTF-8" ?>
<jdeRequest pwd="!" role="*ALL" type="callmethod" user="bkirsch" session="" environment="DV910" sessionidle="15">
<callMethodTemplate name="GetAuditInfo" app="BKJS" />
<endSession />
</jdeRequest>`

My code:
`var xmldoc = new require('xmldoc').XmlDocument(myXmlDocument);`

The error:
`C:\bdk\node-jde\node_modules\xmldoc\lib\xmldoc.js:293
function parser_text() { delegates[0] && delegates[0]._text.apply(delegates[0],arguments) }`
                                                           ^
TypeError: Cannot read property 'apply' of undefined
    at SAXParser.parser_text [as ontext] (C:\bdk\node-jde\node_modules\xmldoc\lib\xmldoc.js:293:60)
    at emit (C:\bdk\node-jde\node_modules\sax\lib\sax.js:640:35)
    at closeText (C:\bdk\node-jde\node_modules\sax\lib\sax.js:650:26)
    at emitNode (C:\bdk\node-jde\node_modules\sax\lib\sax.js:644:26)
    at newTag (C:\bdk\node-jde\node_modules\sax\lib\sax.js:707:5)
    at SAXParser.write (C:\bdk\node-jde\node_modules\sax\lib\sax.js:1292:13)
    at Object.XmlDocument (C:\bdk\node-jde\node_modules\xmldoc\lib\xmldoc.js:251:15)
    at xmlco.execXML (C:\bdk\node-jde\node_modules\jde\xmlco.js:63:23)
    at Object.<anonymous> (C:\bdk\node-jde\jdetester.js:19:18)
    at Module._compile (module.js:571:32)

**Comment by nfarina** [comment]
This is happening due to the way in which you are constructing the `XmlDocument` class. See [this discussion on SO for more information](http://stackoverflow.com/questions/17604497/how-does-require-work-with-new-operator-in-node-js). Try `require`ing the class before instantiating it:

```js
var XmlDocument = require('xmldoc').XmlDocument;

var myXmlDocument = '<?xml version="1.0" encoding="UTF-8" ?> <jdeRequest pwd="!" role="*ALL" type="callmethod" user="bkirsch" session="" environment="DV910" sessionidle="15"> <callMethodTemplate name="GetAuditInfo" app="BKJS" /> <endSession /> </jdeRequest>';

var xmldoc = new XmlDocument(myXmlDocument);
```
